// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export * from "./awsCluster";
export * from "./awsNodePool";
export * from "./azureClient";
export * from "./azureCluster";
export * from "./azureNodePool";
export * from "./cluster";
export * from "./getCluster";
export * from "./getEngineVersions";
export * from "./nodePool";
export * from "./registry";

// Import resources to register:
import { AwsCluster } from "./awsCluster";
import { AwsNodePool } from "./awsNodePool";
import { AzureClient } from "./azureClient";
import { AzureCluster } from "./azureCluster";
import { AzureNodePool } from "./azureNodePool";
import { Cluster } from "./cluster";
import { NodePool } from "./nodePool";
import { Registry } from "./registry";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "google-hybrid:container/classic:AwsCluster":
                return new AwsCluster(name, <any>undefined, { urn })
            case "google-hybrid:container/classic:AwsNodePool":
                return new AwsNodePool(name, <any>undefined, { urn })
            case "google-hybrid:container/classic:AzureClient":
                return new AzureClient(name, <any>undefined, { urn })
            case "google-hybrid:container/classic:AzureCluster":
                return new AzureCluster(name, <any>undefined, { urn })
            case "google-hybrid:container/classic:AzureNodePool":
                return new AzureNodePool(name, <any>undefined, { urn })
            case "google-hybrid:container/classic:Cluster":
                return new Cluster(name, <any>undefined, { urn })
            case "google-hybrid:container/classic:NodePool":
                return new NodePool(name, <any>undefined, { urn })
            case "google-hybrid:container/classic:Registry":
                return new Registry(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("google-hybrid", "container/classic", _module)
