// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

// Export sub-modules:
import * as alpha from "./alpha";
import * as beta from "./beta";
import * as classic from "./classic";
import * as v1 from "./v1";

export {
    alpha,
    beta,
    classic,
    v1,
};
