// *** WARNING: this file was generated by the Pulumi SDK Generator. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../../utilities";

// Export members:
export * from "./accessApprovalSettings";
export * from "./defaultServiceAccounts";
export * from "./iamauditConfig";
export * from "./iambinding";
export * from "./iamcustomRole";
export * from "./iammember";
export * from "./iampolicy";
export * from "./organizationPolicy";
export * from "./service";
export * from "./serviceIdentity";
export * from "./usageExportBucket";

// Import resources to register:
import { AccessApprovalSettings } from "./accessApprovalSettings";
import { DefaultServiceAccounts } from "./defaultServiceAccounts";
import { IAMAuditConfig } from "./iamauditConfig";
import { IAMBinding } from "./iambinding";
import { IAMCustomRole } from "./iamcustomRole";
import { IAMMember } from "./iammember";
import { IAMPolicy } from "./iampolicy";
import { OrganizationPolicy } from "./organizationPolicy";
import { Service } from "./service";
import { ServiceIdentity } from "./serviceIdentity";
import { UsageExportBucket } from "./usageExportBucket";

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "google-hybrid:projects/classic:AccessApprovalSettings":
                return new AccessApprovalSettings(name, <any>undefined, { urn })
            case "google-hybrid:projects/classic:DefaultServiceAccounts":
                return new DefaultServiceAccounts(name, <any>undefined, { urn })
            case "google-hybrid:projects/classic:IAMAuditConfig":
                return new IAMAuditConfig(name, <any>undefined, { urn })
            case "google-hybrid:projects/classic:IAMBinding":
                return new IAMBinding(name, <any>undefined, { urn })
            case "google-hybrid:projects/classic:IAMCustomRole":
                return new IAMCustomRole(name, <any>undefined, { urn })
            case "google-hybrid:projects/classic:IAMMember":
                return new IAMMember(name, <any>undefined, { urn })
            case "google-hybrid:projects/classic:IAMPolicy":
                return new IAMPolicy(name, <any>undefined, { urn })
            case "google-hybrid:projects/classic:OrganizationPolicy":
                return new OrganizationPolicy(name, <any>undefined, { urn })
            case "google-hybrid:projects/classic:Service":
                return new Service(name, <any>undefined, { urn })
            case "google-hybrid:projects/classic:ServiceIdentity":
                return new ServiceIdentity(name, <any>undefined, { urn })
            case "google-hybrid:projects/classic:UsageExportBucket":
                return new UsageExportBucket(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("google-hybrid", "projects/classic", _module)
